/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    OmButton: typeof import('omnius-ui-uni/lib/components/om-button/om-button.vue')['default']
    OmWrapper: typeof import('omnius-ui-uni/lib/components/om-wrapper/om-wrapper.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
