/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    OmBlock: (typeof import('./../src/components/om-block/om-block.vue'))['default']
    OmButton: (typeof import('@omnius-uni/ui/lib/components/om-button/om-button.vue'))['default']
    OmWrapper: (typeof import('@omnius-uni/ui/lib/components/om-wrapper/om-wrapper.vue'))['default']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
  }
}
